apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
type: Opaque
data:
  is-production: <BASE64_ENCODED_VALUE>
  payu-key-test: <BASE64_ENCODED_VALUE>
  payu-key-prod: <BASE64_ENCODED_VALUE>
